### PR TITLE
Class as xml externalization

### PR DESCRIPTION
**Pull request by akryvtsun**
The 3th PR attempt with Qulice checks satisfaction

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#370](https://github.com/yegor256/jpeek/issues/370) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#370](https://github.com/yegor256/jpeek/issues/370) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/55bcb1b1-958a-4022-a733-0c31a2264334); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#370` already assigned to @fabriciofx, can't assign to @fabriciofx

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#370](https://github.com/yegor256/jpeek/issues/370) is already in the agenda of @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#370](https://github.com/yegor256/jpeek/issues/370) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Pull request merged**
