### PR TITLE
Update Readme for LCOM2-3

### PR DESCRIPTION
**Pull request by memoyil**
Update Readme for LCOM 2-3

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#48` is in scope.

**Comment by yegor256** [comment]
@rultor merge

**Comment by memoyil** [comment]
@yegor256 Could you please merge with like that? Cause there is a problem with pdf. When I find the correct encoded pdf I will upload it.

**Comment by yegor256** [comment]
@memoyil there are some merge conflicts, can you please fix them?

**Comment by memoyil** [comment]
@yegor256 Fixed

**Comment by yegor256** [comment]
@memoyil thanks!

**Pull request merged**
