### PR TITLE
(#227) Refactor setting schema reference attribute

### PR DESCRIPTION
**Pull request by Protagores**
As per #227:

Refactored the addition of `xsi:noNamespaceSchemaLocation` to generated `metric.xml` into applying a few Xembly instructions instead of an XSL transformation.

Three instructions were eventually needed—one to point the cursor to the `metric` element (since it points _above_ the root element by default), one to declare the XML namespace of the schema location attribute, and one to set the location itself.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#325](https://github.com/yegor256/jpeek/issues/325) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#325](https://github.com/yegor256/jpeek/issues/325) is assigned to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/c491d733-e03f-47d1-95a4-1434e7108460); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by ilyakharlamov** [comment]
@Protagores Are you sure you want to create a pull request from your master? That's usually a bad practice because you will not be able to change anything else, you will not be able to fix any other bug without affecting this issue. I recommend you to cancel this pull request, create a separate branch exclusively for this issue #227, make the fixes only in that branch and submit a new pull request.

**Comment by Protagores** [comment]
@ilyakharlamov 
> I recommend you to cancel this pull request, create a separate branch exclusively for this issue #227, make the fixes only in that branch and submit a new pull request.

Done, see #326

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Pull request [#325](https://github.com/yegor256/jpeek/issues/325) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by 0crat** [comment]
Job [#325](https://github.com/yegor256/jpeek/issues/325) is not in the agenda of @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), can't inspect

**Comment by 0crat** [comment]
The job [#325](https://github.com/yegor256/jpeek/issues/325) is now out of scope

**Comment by fabriciofx** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Pull request closed without merging**
