### PR TITLE
(#315) replaced Broken RawGit links

### PR DESCRIPTION
**Pull request by mohamednizar**
(#315) replaced Broken RawGit links

### CODE REVIEW

**Comment by 0crat** [comment]
@mohamednizar[/z](https://www.0crat.com/u/mohamednizar) this pull request is too small, just 6 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by mohamednizar** [comment]
@0crat wait

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#354` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30.2`

**Pull request merged**
