### PR TITLE
(#111) Advancing research for LORM implementation

### PR DESCRIPTION
**Pull request by llorllale**
as per #111

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#184](https://github.com/yegor256/jpeek/issues/184) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#184](https://github.com/yegor256/jpeek/issues/184) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/451943694). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by amihaiemil** [comment]
@llorllale Looks ok, thanks. But there is a problem (not your fault). This research should have been done in the context of the ticket https://github.com/yegor256/jpeek/issues/160. Then, that puzzle should have been removed and replaced with the one you added here. 

The task you had now was to implement LORM and use it in reporting. And it is stated that this task has impediments. 

Anyway, quite complex, 0crat needs improvements still, to know which task to assign and which not...

**Comment by amihaiemil** [comment]
@rultor goog to merge

**Comment by llorllale** [comment]
@amihaiemil 
> And it is stated that this task has impediments -- I'm not sure what to do in this situation? 

See comments starting at [this](https://github.com/yegor256/jpeek/issues/118#issuecomment-363800692) one

**Comment by amihaiemil** [comment]
@llorllale I see, ok :)

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by llorllale** [comment]
@amihaiemil any advice on how to fix this build error? How can I have changed the coverage when all I modified were an XSL and removed a comment in `App.java`?

**Comment by amihaiemil** [comment]
@llorllale as the logs say, it fails because ``jacoco`` detected a lower test coverage than allowed: ``Rule violated for bundle jpeek: lines covered ratio is 0.62, but expected minimum is 0.67``

Yes, your PR did not alter code coverage. Maybe it was changed in an earlier PR which was merged before this.

I would say: open a ticket about this, instruct 0crat to wait on your task and close this PR in the meantime (but don't delete your branch so you can make another PR after that ticket is solved).

**Comment by amihaiemil** [comment]
@llorllale It also happened here: https://github.com/yegor256/jpeek/pull/179

**Comment by llorllale** [comment]
Closing while waiting on #192

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by llorllale** [comment]
0crat must be having a hangover :)

**Comment by amihaiemil** [comment]
@llorllale yes, I guess in the case of PRs, the QA reviews the job done by the CR. I hope I did the right thing here, advised you properly (that's what seemed logical to me).

**Comment by llorllale** [comment]
FYI just opened #197

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ypshenychka** [comment]
@llorllale According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
1. >Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

Please provide more details in description.

2. >Messages in a ticket always start with a name of a user they are addressed to.

Please correct your messages by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by amihaiemil** [comment]
@ypshenychka I confirm I'll try to find more issues in future tasks

**Comment by llorllale** [comment]
@ypshenychka fixed description and my messages

**Comment by ypshenychka** [comment]
@llorllale Thank you!

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+345](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+805](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10349](https://www.0crat.com/u/yegor256)

**Pull request closed without merging**
