### PR TITLE
Added test cases for CCM

### PR DESCRIPTION
**Pull request by oridan**
PR for #147 
Added the folowing test cases for CCM:
- NoMethods
- WithoutAttributes
- OneMethodCreatesLambda
- OneVoidMethodWithoutParams

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#235](https://github.com/yegor256/jpeek/issues/235) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at [#235](https://github.com/yegor256/jpeek/issues/235); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#235](https://github.com/yegor256/jpeek/issues/235); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@oridan looks like the problem is in your branch. Did you manage to build it locally?

**Comment by 0crat** [comment]
This pull request [#235](https://github.com/yegor256/jpeek/issues/235) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1480779290); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewercom.zerocracy.Par@56559e5

**Comment by paulodamaso** [comment]
@oridan Please resolve conflicts.

**Comment by oridan** [comment]
@paulodamaso, I have solved the conflicts, please take a look.

**Comment by paulodamaso** [comment]
@oridan Looks like that's all right, thanks.

**Comment by paulodamaso** [comment]
@rultor please merge

**Comment by paulodamaso** [comment]
@yegor256 This PR is good to merge.

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for merge

**Comment by 0crat** [comment]
> @0crat wait for merge ([here](https://github.com/yegor256/jpeek/issues/235#issuecomment-394114463))

@paulodamaso It's a code review job [#235](https://github.com/yegor256/jpeek/issues/235), can't put it on hold

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#235](https://github.com/yegor256/jpeek/issues/235) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by elenavolokhova** [comment]
@paulodamaso According to our Policy:
> The code reviewer found at least three problems in the code

Only one issue was found in this review. Please, confirm that you will try to find at least three problems next time.

**Comment by elenavolokhova** [comment]
@oridan According to our Policy:

> All commit messages have links to issues

Please, confirm that you will follow this rule in future. Thanks!

**Comment by paulodamaso** [comment]
@elenavolokhova confirm

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
