### PR TITLE
#470 - Fixed LORM XSL.

### PR DESCRIPTION
**Pull request by vzurauskas**
PR for #470 

Fixed the XSL to work with new skeleton structure and re-enabled the test.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#471](https://github.com/yegor256/jpeek/issues/471) is assigned to @iiylll[/z](https://www.0crat.com/u/iiylll), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/55d25351-c37c-47bd-b00c-4395bddc163c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@iiylll[/z](https://www.0crat.com/u/iiylll) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by vzurauskas** [comment]
@iiylll ping

**Comment by paulodamaso** [comment]
@vzurauskas Thanks, sorry for the delay.

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @iiylll[/z](https://www.0crat.com/u/iiylll), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Code review was too long (19 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
