### PR TITLE
#23 Change CAMC Calculation

### PR DESCRIPTION
**Pull request by memoyil**
Changed CAMC algorithm in the code based on this image

[](http://blog.sdmetrics.com/wp-content/uploads/2012/04/pom.png)

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#29` is in scope.

**Comment by yegor256** [comment]
@memoyil how do you know the bug is fixed? Did you manage to reproduce it in a test?

**Comment by memoyil** [comment]
@yegor256 Could you provide me classes that produce that error?

**Comment by yegor256** [comment]
@memoyil sure, look: http://i.jpeek.org/org.takes/takes/CAMC.html

**Comment by memoyil** [comment]
@yegor256 It is working now you can see it on the screenshot.

capture

**Comment by yegor256** [comment]
@memoyil we have to reproduce this bug in a test :) Without a test, we will repeat it again very soon. Try to create a similar class, somewhere close to `Foo.java` and you will see the bug. Then, fix it and the test will pass

**Comment by memoyil** [comment]
@yegor256 I have added test cases.

**Comment by memoyil** [comment]
@yegor256 Could you please help me to find out the problem? I couldn't see any error in my machine. But in build machine there is an error.

**Comment by yegor256** [comment]
@memoyil you need to merge master branch into your branch and you will see the error in your machine too.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
