### PR TITLE
#313 bump jcabi parent version to 0.49.9

### PR DESCRIPTION
**Pull request by victornoel**
This is for #313.

According to jcabi changelog, this was fixed since 0.49.2 (most certainly with 0.49.5 but changelog is not extremely clear).

Since
- 0.49.2 was released before #313 was opened
- 0.49.9 was released after #313 was opened

I believe this should be alright to answer the ticket submitter request for using latest snapshot at the time.

### CODE REVIEW

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by victornoel** [comment]
@paulodamaso please wait for review, it seems the build is now broken :)

**Comment by victornoel** [comment]
@paulodamaso it should be fixed.

Note that:
- I had to keep the version of hamcrest-core and co to the old one because the new one has the needed dependency for `compile` in hamcrest instead of hamcrest-core, which then, if added to the compile scope, would make qulice complain
- I took the opportunity to use the version of junit recommended by jcabi parent, which remove the deprecated `org.junit.Test` annotation, hence the change in the code for tests to work.

**Comment by paulodamaso** [comment]
@victornoel Thanks!

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#434` is not assigned, can't get performer

**Pull request merged**
