### PR TITLE
#118 LCC metric has impediments

### PR DESCRIPTION
**Pull request by SharplEr**
For #118 

**Problem**
LCC metric has impediments. Need to wait for resolving these impediments, add LCC to reports list and cover it by tests.

**Work which I did**
1. Added a new class for test `IndirectlyRelatedPairs` which should work differently on LCC and TCC metrics.
2. Added new puzzles to fix a bug in `LCC.xsl` where even number of direct connection calculates wrong.
3. Fixed title in `LCC.xsl`.
4. Fixed a value formatting in `TCC.xsl` because it doesn't work well with my `IndirectlyRelatedPairs`.
5. Recreated the original puzzle about adding to reports list. But without testing part.

**P.S.**
It is my first PR with PDD.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#231](https://github.com/yegor256/jpeek/issues/231) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at [#231](https://github.com/yegor256/jpeek/issues/231); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#231](https://github.com/yegor256/jpeek/issues/231); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@SharplEr I believe the branch has problems. Try to run `pdd -v -f /dev/null` locally.

**Comment by SharplEr** [comment]
@yegor256 Try again. Now should work. But looks like @uurl  now works on this task. If my PR no need, I can close it.

**Comment by 0crat** [comment]
This pull request [#231](https://github.com/yegor256/jpeek/issues/231) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1480776200); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewercom.zerocracy.Par@3646614d

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#231](https://github.com/yegor256/jpeek/issues/231) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by paulodamaso** [comment]
@llorllale @yegor256 What I'm supposed to review here? The PR has already been merged.

**Comment by llorllale** [comment]
@paulodamaso I'm not the `ARC` of this project

**Comment by paulodamaso** [comment]
@llorllale Sorry, I've mixed some projects here.

**Comment by elenavolokhova** [comment]
@0crat quality bad as performer was assigned after PR was already merged and review was not completed as expected.

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
