### PR TITLE
Update maven-compiler-plugin to 3.8.0

### PR DESCRIPTION
**Pull request by akryvtsun**
This PR is related to issue #324 and allows incremental compilation for `maven-compiler-plugin` adding appropriate plugin key into `pom.xml`

### CODE REVIEW

**Comment by 0crat** [comment]
@akryvtsun[/z](https://www.0crat.com/u/akryvtsun) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by akryvtsun** [comment]
Strange fail for me: haven't touched Java code at all

**Comment by paulodamaso** [comment]
@akryvtsun Codecov sometimes shows these strange failures; please just change the title of your PR linking it to the issue you are solving and update the PR description, putting the issue number it is proposed to solve and what you have done to solve it

**Comment by akryvtsun** [comment]
@paulodamaso done

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#367` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
