### PR TITLE
#355 Add puzzles check on travis

### PR DESCRIPTION
**Pull request by HDouss**
Ressolving issue #355 
Travis lacks pdd checks.
The PR consists of ~3~ 4 commits:
* 23bdbd7 and 1e082eb : add badly worded puzzle -> we see here that travis accepts it
* 8c1337c : fix travis build script -> Travis is now failing
* cd51569 : remove the badly worded puzzle introduced in 23bdbd7 and 1e082eb, so everything is back to normal

### CODE REVIEW

**Comment by 0crat** [comment]
@HDouss this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by paulodamaso** [comment]
@HDouss great, thanks

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#387` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
