### PR TITLE
Update rultor.yml with architect info

### PR DESCRIPTION
**Pull request by paulodamaso**
Updated `rultor.yml`  with my architect info, at the moment I can't ask rultor to merge PRs

### CODE REVIEW

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by yegor256** [comment]
@paulodamaso done

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#281` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
