### PR TITLE
#111 Advancing research for LORM implementation

### PR DESCRIPTION
**Pull request by llorllale**
as per #111

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#197](https://github.com/yegor256/jpeek/issues/197) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#197](https://github.com/yegor256/jpeek/issues/197) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/491445979). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by amihaiemil** [comment]
@llorllale was the unit test coverage problem solved?

**Comment by llorllale** [comment]
@amihaiemil apparently yes, although there was no feedback on the issue i opened for it

**Comment by amihaiemil** [comment]
@llorllale I see, ok.

**Comment by amihaiemil** [comment]
@yegor256 The author reopened the PR (it had been opened a few days ago initially, but closed since it could not be merged due to #192. Now, it seems that that ticket is solved. This can be merged.

**Comment by llorllale** [comment]
@yegor256 please merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by amihaiemil** [comment]
@ypshenychka ping

**Comment by ypshenychka** [comment]
@llorllale According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

Please provide more details on PR's desription.

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by amihaiemil** [comment]
@ypshenychka yes, I confirm (I actually opened a ticket in zerocracy/farm, a CR is not always needed, esp. for such small PRs). 

@llorllale please, add a few words in the description (I think the one from the previous PR is ok, you had some links there)

**Comment by ypshenychka** [comment]
@amihaiemil If the PR is too small it should be combined with other related issue and fixed. It would be a high quality ticket.

**Comment by amihaiemil** [comment]
@ypshenychka 

> it should be combined with other related issue and fixed.

Not sure how that would help -- a PR may be small because its ticket points out a small issue. How do you combine it with other PRs? I think it would just turn into a Github Issue-spaghetti. Much easier if we keep each ticket isolated and only assign CR where changes are bigger :D

**Comment by ypshenychka** [comment]
@amihaiemil Let's ask @yegor256 what he thinks about this.

**Comment by amihaiemil** [comment]
@ypshenychka I guess we can discuss that in the opened ticket. Let's hope @llorllale edits the description here so we can close this...

**Comment by llorllale** [comment]
@ypshenychka fixed description

**Comment by ypshenychka** [comment]
@llorllale Thank you!

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/jpeek/issues/197#issuecomment-367662708))

@ypshenychka There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.zerocracy.pmo.banks.Crypto[144] java.io.IOException: Failed to buy at Coinbase
com.coinbase.api.CoinbaseImpl[1330] com.coinbase.api.exception.CoinbaseException: Your account has been locked, please visit coinbase.com to resolve
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+555](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+920](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/jpeek/issues/197#issuecomment-367662708))

@ypshenychka You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: QA.

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10679](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
This pull request [#197](https://github.com/yegor256/jpeek/issues/197) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/531239648). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by amihaiemil** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/197#issuecomment-367778798))

@amihaiemil This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#197](https://github.com/yegor256/jpeek/issues/197) is [in scope](http://www.zerocracy.com/policy.html#14) for 4days
  * The role is `REV`
  * The job is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) for [6hr](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) will get 25% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @llorllale[/z](https://www.0crat.com/u/llorllale): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23197%27%7D) (restricted area)

**Comment by amihaiemil** [comment]
@yegor256 Could you also resign me here?

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/197#issuecomment-368837150))

@yegor256 The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#197](https://github.com/yegor256/jpeek/issues/197), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/jpeek/issues/197#issuecomment-368837231))

@yegor256 The job [#197](https://github.com/yegor256/jpeek/issues/197) is now out of scope

**Pull request merged**
