### PR TITLE
#216 add more tests on LCOM4

### PR DESCRIPTION
**Pull request by verkhovin**
This PR (#216 ) :

- Adds three new test cases on LCOM4:  `OneCommonAttribute`, `NotCommonAttributes`, `NotCommonAttributesWithAllArgsConstructor`
- Leaves puzzle for implementing the rest of the test cases
- Leaves puzzle in order to fix constructors' affection on LCOM4

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#278](https://github.com/yegor256/jpeek/issues/278) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#278](https://github.com/yegor256/jpeek/issues/278); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#278](https://github.com/yegor256/jpeek/issues/278); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#278](https://github.com/yegor256/jpeek/issues/278); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) everybody who has role `REV` is banned at [#278](https://github.com/yegor256/jpeek/issues/278); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@0crat assign me

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@verkhovin Please correct puzzle indentation

**Comment by paulodamaso** [comment]
@verkhovin ping

**Comment by paulodamaso** [comment]
@verkhovin your puzzle indentation is breaking the build, please take a look

**Comment by verkhovin** [comment]
@paulodamaso sorry, I missed this one. I will take a look in the nearest future

**Comment by verkhovin** [comment]
@paulodamaso done

**Comment by paulodamaso** [comment]
@verkhovin Thanks!

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Code review was too long (21 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
The job [#278](https://github.com/yegor256/jpeek/issues/278) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Pull request merged**
