### PR TITLE
NHD Metric Implementation

### PR DESCRIPTION
**Pull request by memoyil**
NHD Metric Implementation

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#34` is in scope.

**Comment by yegor256** [comment]
@memoyil looks good, let me merge it

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@memoyil can you please update README and add PDF for this metric too? Thanks!

**Comment by memoyil** [comment]
@yegor256 sure

**Pull request merged**
