### PR TITLE
issue #333 renaming papers files according to metrics

### PR DESCRIPTION
**Pull request by HDouss**
Resolving issue #333 
izadkhah17.pdf was not renamed because it does not introduce any new metric. It compares state of the art existent metrics.

### CODE REVIEW

**Comment by 0crat** [comment]
@HDouss this pull request is too small, just 0 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by HDouss** [comment]
@paulodamaso ping

**Comment by paulodamaso** [comment]
@HDouss Thank you

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#383` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
