### PR TITLE
#171: Ignore bridge methods

### PR DESCRIPTION
**Pull request by ilyakharlamov**
https://github.com/yegor256/jpeek/issues/171

Java compiler produces multiple synthetic methods from a single Java method which incorrectly lowers the LCC and LCOM2 scores.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#270](https://github.com/yegor256/jpeek/issues/270) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#270](https://github.com/yegor256/jpeek/issues/270); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#270](https://github.com/yegor256/jpeek/issues/270); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#270](https://github.com/yegor256/jpeek/issues/270); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#270](https://github.com/yegor256/jpeek/issues/270); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#270](https://github.com/yegor256/jpeek/issues/270); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#270](https://github.com/yegor256/jpeek/issues/270); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by Serranya** [comment]
@0crat quality bad

@ilyakharlamov Qualice is not letting this PR pass. Please fix the following errors first:
```
[INFO] Checkstyle: src/main/java/org/jpeek/skeleton/XmlClass.java[154]: Return count is 2 (max allowed is 1). (ReturnCountCheck)
[INFO] Checkstyle: src/main/java/org/jpeek/skeleton/XmlClass.java[164]: Line is longer than 80 characters (found 102). (LineLengthCheck)
[INFO] Checkstyle: src/main/java/org/jpeek/skeleton/XmlClass.java[164]: Name 'visitMethod' must match pattern '^(id|[a-z]{3,12})$'. (LocalFinalVariableNameCheck)
[INFO] Checkstyle: src/main/java/org/jpeek/skeleton/XmlClass.java[165]: '(' is followed by whitespace. (ParenPadCheck)
[INFO] Checkstyle: src/main/java/org/jpeek/skeleton/XmlClass.java[168]: Method call to 'directives' needs "this.". (RequireThisCheck)
[INFO] Checkstyle: src/main/java/org/jpeek/skeleton/XmlClass.java[176]: Line is longer than 80 characters (found 90). (LineLengthCheck)
[INFO] Checkstyle: src/main/java/org/jpeek/skeleton/XmlClass.java[176]: This method must be static, because it does not refer to "this" (NonStaticMethodCheck)
[INFO] Checkstyle: src/main/java/org/jpeek/skeleton/XmlClass.java[176]: Missing a Javadoc comment. (JavadocMethodCheck)
[INFO] Checkstyle: src/main/java/org/jpeek/skeleton/XmlClass.java[202]: 'method def rcurly' have incorrect indentation level 8, expected level should be 4. (IndentationCheck)
[INFO] Checkstyle: src/main/java/org/jpeek/skeleton/XmlClass.java[202]: Line contains a tab character. (FileTabCharacterCheck)
[INFO] Checkstyle: src/test/java/org/jpeek/skeleton/SkeletonTest.java[109]: Two consecutive empty lines (RegexpMultilineCheck)
[INFO] Checkstyle: src/test/java/org/jpeek/skeleton/SkeletonTest.java[121]: Line is longer than 80 characters (found 114). (LineLengthCheck)
```
(you can see these errors in the travis build)

You can also test if qualice checks are passing locally. Just use maven with ` -Pqulice`

**Comment by 0crat** [comment]
> @0crat quality bad @ilyakharlamov Qualice is not letting this PR pass. Please fix the followin... ([here](https://github.com/yegor256/jpeek/issues/270#issuecomment-442754866))

@Serranya You can't do "Complete `QA` review", unless you have one of these roles: `ARC`, `QA`; current roles of @serranya[/z](https://www.0crat.com/u/serranya) are: `DEV`

**Comment by Serranya** [comment]
@yegor256 Seems like I can't review this anymore. I got the `REV` role and this PR. After this my `REV` role was immediately revoked.

**Comment by Serranya** [comment]
@yegor256 The author of this PR is not on Zerocracy anymore and has not responded in the last 4 days. I think this PR should not be merged.

**Comment by ilyakharlamov** [comment]
>  The author of this PR is not on Zerocracy anymore and has not responded in the last 4 days. I think this PR should not be merged.

Hang on, I am around and still in Zerocracy.
In order to respond, someone else needs to post a question first, isn't it?

For sure this PR should not be merged because it violates some linting checks. 
I'll submit another version of this PR, no problem.

**Comment by Serranya** [comment]
@ilyakharlamov Ahh sorry. I don't not see you in the team list at https://www.0crat.com/team

**Comment by Serranya** [comment]
@ilyakharlamov I dont think you need to open another one. Just fix the problems I mentioned here: 
https://github.com/yegor256/jpeek/pull/270#issuecomment-442754866

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by paulodamaso** [comment]
@0crat assign @Serranya

**Comment by 0crat** [comment]
> @0crat assign @Serranya  ([here](https://github.com/yegor256/jpeek/issues/270#issuecomment-447392236))

@paulodamaso Job [#270](https://github.com/yegor256/jpeek/issues/270) is already assigned to @serranya[/z](https://www.0crat.com/u/serranya)

**Comment by paulodamaso** [comment]
@Serranya How is the status of this one? Can we merge it?

**Comment by Serranya** [comment]
@paulodamaso Looks good to me. I approve

**Comment by paulodamaso** [comment]
@Serranya Thanks

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31):

**Comment by 0crat** [comment]
Code review was too long (16 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
The job [#270](https://github.com/yegor256/jpeek/issues/270) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Pull request merged**
