### PR TITLE
#91 implement MMAC via XML/XSL

### PR DESCRIPTION
**Pull request by vmotsak**
XML/XSL implementation of MMAC metric, based on Java implementation in #14

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#95](https://github.com/yegor256/jpeek/issues/95) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#95](https://github.com/yegor256/jpeek/issues/95) is assigned to @amihaiemil[/z](http://www.0crat.com/u/amihaiemil). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and [§10](http://datum.zerocracy.com/pages/policy.html#10) and when you decide to accept the changes, inform @yegor256[/z](http://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by amihaiemil** [comment]
@vmotsak I don't like it; but it's not your fault, the app's architecture is too monolithic, I believe. 

First off, how is this measurement you implemented actually tested? You just added some parameters to that generic tests (which apparently tests all the metrics together...?) and validate only the output's format? What about the value of this metric you implemented, which is supposed to be between 0 and 1? Is that tested? 

Nevertheless, this all seems a problem of architecture, **maybe you could open some tickets**? I would implement each report in its own class, rather than have that ``Report`` class which iterates over XMLs -- testing is hard this way. 

About this PR: 

1) Add a description, what is this measurement exactly? You could add a summary of that big comment from the XML. 

2) The copyright in the header of the Xml, should be 2017-2018

Otherwise, it looks ok...

**Comment by vmotsak** [comment]
@amihaiemil 

yes `MetricsTest` tests new MMAC values, including ones between 0 and 1.
eg [MetricsTest.java:78](https://github.com/vmotsak/jpeek/blob/3087dc93ca261949d02d892f40e9e321c2b0d09e/src/test/java/org/jpeek/MetricsTest.java#L78)

>I would implement each report in its own class

What you are suggesting was before this change to XML/XSL, each metric had its own class and test.

 >2. The copyright in the header ...

As I see work already started to address this [PR#87](https://github.com/yegor256/jpeek/pull/87)

**Comment by amihaiemil** [comment]
> As I see work already started to address this

@vmotsak Yes, there is that PR for updating the years, but it covers the existing files at the moment of the task's creation, not also future files. Since this is a new file, it should have the correct stuff to begin with.

**Comment by vmotsak** [comment]
As I understand license file header checked by qulice based on /LICENSE.TXT
making the year change to the only one file will break the build.
> For instance, that PR may be merged now
If you can merge it now, I can fix year in XSL file header

**Comment by amihaiemil** [comment]
@vmotsak ok then, let's leave that for later

**Comment by amihaiemil** [comment]
@rultor good to merge

**Comment by amihaiemil** [comment]
@yegor256 ping; this one is good to merge :)

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+30](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7735](https://www.0crat.com/u/yegor256)

**Pull request merged**
