### PR TITLE
#103 Adding support for NaN in MetricsTest

### PR DESCRIPTION
**Pull request by skapral**
Fix for #103.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#161](https://github.com/yegor256/jpeek/issues/161) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#161](https://github.com/yegor256/jpeek/issues/161) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by amihaiemil** [comment]
@skapral looks ok to me :)

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by amihaiemil** [comment]
@skapral There is conflict now with master, can you check?

**Comment by amihaiemil** [comment]
@skapral ping ;)

**Comment by skapral** [comment]
@amihaiemil fixed. However I was resigned from the job so probably this PR is not actual anymore. @yegor256?

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+570](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9664](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#161](https://github.com/yegor256/jpeek/issues/161) is now out of scope

**Pull request merged**
