### PR TITLE
(#139) LCOM3: advancing research on impediment for testing OneMethodCreatesLambda

### PR DESCRIPTION
**Pull request by llorllale**
as per #139 

Upon research I found that the compiler creates "synthetic" methods (also known as "bridge" methods) as per [JLS 13.1](https://docs.oracle.com/javase/specs/jls/se8/html/jls-13.html#jls-13.1):

> A construct emitted by a Java compiler must be marked as synthetic if it does not correspond to a construct declared explicitly or implicitly in source code, unless the emitted construct is a class initialization method (JVMS §2.9). 

Synthetic methods were mostly known for generics (they are necessary due to type erasure), but are also used under the hood for lambdas.

What needs to be done is to exclude these synthetic methods from the `skeleton.xml` in #171 in order to avoid distortions in metric results.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#198](https://github.com/yegor256/jpeek/issues/198) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#198](https://github.com/yegor256/jpeek/issues/198) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/491813778). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by llorllale** [comment]
@amihaiemil please review

**Comment by amihaiemil** [comment]
@llorllale looks good :)

**Comment by amihaiemil** [comment]
@rultor good to merge

**Comment by amihaiemil** [comment]
@llorllale Pls write a few words in the PR's decription (we've seen that the QA complains about that) :)

**Comment by llorllale** [comment]
@amihaiemil fixed description

**Comment by amihaiemil** [comment]
@yegor256 can we merge it?

**Comment by yegor256** [comment]
@llorllale I don't see what this puzzle adds to the problem we had before. Let's just wait for #171 and solve the problem properly. Now we are just reformulating the puzzle. It's not moving us forward anyhow. Am I wrong?

**Comment by llorllale** [comment]
@yegor256 I did research, figured out the problem (which indeed needs to be fixed in #171), and put the puzzle right where the fix needs to take place

What else should I have done here?

**Comment by yegor256** [comment]
@llorllale you should just put #139 on hold and wait for #171. When it's fixed, you just fix #139. It's pointless to create a puzzle when the problem is already documented in #171 See the logic?

**Comment by llorllale** [comment]
@yegor256 what I don't understand is, if this job has a known impediment upfront and there's nothing more to do with it, why was it added to the scope?

I don't know when #171 will be fixed. Declaring an impediment on this job will then leave it occupying one of my slots doing nothing. It would be more useful if I could instead be able to refuse this job *without* penalty points and accept another job.

**Comment by amihaiemil** [comment]
@yegor256 I agree with the author, 0crat should look for keywords such as "impediment" in a new Issue's description. As we've seen, this is the case with many Issues in jpeek.

**Comment by yegor256** [comment]
@llorllale I understand the problem, but it's not an excuse. The first option would be to put the ticket on hold (occupying your slot). The second option would be to move the project forward __more__ than you did. Maybe by adding more documentation to the puzzle. Or maybe by writing some additional tests. Something.

**Comment by llorllale** [comment]
@yegor256 There are no more tests left for LCOM3 (test for `Bar` is being address in a separate, open PR).

What I can do now is basically include the solution for #171 inside the text of the new puzzle I've created in this PR. 

Would that suffice?

**Comment by yegor256** [comment]
@llorllale yes, that will work

**Comment by llorllale** [comment]
@yegor256 I expanded a bit on the puzzle basically laid out what needs to be done, basing myself on the [documentation](http://asm.ow2.org/asm60/javadoc/user/org/objectweb/asm/ClassVisitor.html#visitMethod-int-java.lang.String-java.lang.String-java.lang.String-java.lang.String:A-) available.

I hope it's OK now.

**Comment by llorllale** [comment]
ping @yegor256

**Comment by yegor256** [comment]
@llorllale @amihaiemil I still don't understand what is the contribution of this PR. We had a puzzle, which said exactly what the new puzzle is saying: the skeleton is broken. When the skeleton will be fixed, we will fix this puzzle. What is the point of removing one puzzle and adding a new one, saying almost exactly the same?

**Comment by amihaiemil** [comment]
@yegor256 well, the new puzzle is a bit more detailed and it has another parent ticket than the original one. It can be traced to the Issue of this PR, where @llorllale did more research and wrote his findings in the description. I would say it's an advancement; maybe not big, but an advancement :)

**Comment by yegor256** [comment]
@llorllale @amihaiemil OK, I'm merging

**Comment by yegor256** [comment]
@rultor merge

**Comment by llorllale** [comment]
@yegor256 @amihaiemil reopened #192

**Comment by llorllale** [comment]
@yegor256 like I mentioned in #192, this may be an intermittent issue. Can you please try merging again just in case it works this time around?

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@amihaiemil fixed conflicts, please review

**Comment by amihaiemil** [comment]
@yegor256 can we try to merge again?

**Comment by llorllale** [comment]
ping @yegor256

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@llorllale conflict again here... we really have to fix that MetricsTest stuff :/

**Comment by llorllale** [comment]
@amihaiemil fixed conflicts, please review

**Comment by amihaiemil** [comment]
@yegor256 Can we merge this? 10th day...

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by 0crat** [comment]
The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#198](https://github.com/yegor256/jpeek/issues/198), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+1130](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Mistake of @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)[/z](https://www.0crat.com/u/amihaiemil) (your student): Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+11014](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#198](https://github.com/yegor256/jpeek/issues/198) is now out of scope

**Pull request merged**
