### PR TITLE
#118 LCC metric has impediments

### PR DESCRIPTION
**Pull request by uurl**
For #118

**Issue**
LCC metric has impediments. Need to wait for resolving these impediments, add LCC to reports list and cover it by tests.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#242](https://github.com/yegor256/jpeek/issues/242) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#242](https://github.com/yegor256/jpeek/issues/242); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#242](https://github.com/yegor256/jpeek/issues/242) is now out of scope

**Pull request merged**
