### PR TITLE
#282 add documentation to bars and bar tags

### PR DESCRIPTION
**Pull request by GnusinPavel**

### CODE REVIEW

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#337](https://github.com/yegor256/jpeek/issues/337) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) everybody who has role `REV` is banned at [#337](https://github.com/yegor256/jpeek/issues/337); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
This pull request [#337](https://github.com/yegor256/jpeek/issues/337) is assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/f9733efc-52d5-4e65-8a03-0500f5b8e81c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by GnusinPavel** [comment]
@mohamednizar can you review this pull request?

**Comment by mohamednizar** [comment]
@GnusinPavel , I don't have `REV` role this project. Please ping the `ARC`.

**Comment by GnusinPavel** [comment]
> This pull request [#337](https://github.com/yegor256/jpeek/issues/337) is assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/f9733efc-52d5-4e65-8a03-0500f5b8e81c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

It seems strange )) @paulodamaso  what can you say?

**Comment by paulodamaso** [comment]
@mohamednizar Please go on with the review. 0crat auto-assign `REV` to members when I ask to it assign `DEV` role, so it assigned `REV` role to you, assigned the issue, and unassigned `REV` role.

**Comment by paulodamaso** [comment]
@GnusinPavel @mohamednizar Thanks!

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#337](https://github.com/yegor256/jpeek/issues/337) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by mohamednizar** [comment]
@fabriciofx , can you confirm the quality please ?

**Comment by mohamednizar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/337#issuecomment-538963094))

@mohamednizar This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#337](https://github.com/yegor256/jpeek/issues/337) is not in scope
  * The job is waiting quality review verdict by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for 18hr
  * @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) will receive 15 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23337%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by GnusinPavel** [comment]
@fabriciofx ping

**Comment by paulodamaso** [comment]
@fabriciofx please go on

**Comment by fabriciofx** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +20 point(s) just awarded to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)

**Pull request merged**
