### PR TITLE
#224 add a reference to this schema from the generated skeleton.xml

### PR DESCRIPTION
**Pull request by stepanov-dmitry**
Desciption:    
    1. The puzzle has been removed since the issue has been done
    in the pull request #339.

### CODE REVIEW

**Comment by 0crat** [comment]
@stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by stepanov-dmitry** [comment]
@paulodamaso @mohamednizar could you please merge it since the task was already done in the scope of #339 ?

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#352` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
