### PR TITLE
#338 Travis build doesn't work anymore

### PR DESCRIPTION
**Pull request by mohamednizar**
A new fix added to .travis.yml to resolve the build issue.

### CODE REVIEW

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this pull request

**Comment by 0crat** [comment]
@mohamednizar[/z](https://www.0crat.com/u/mohamednizar) this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by mohamednizar** [comment]
@paulodamaso , I did not find any one working on this issue, can't we merge this ?  since I'm waiting for create another pull request.

**Comment by paulodamaso** [comment]
@mohamednizar Thanks!

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#344` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by mohamednizar** [comment]
@paulodamaso  , I didn't get reputation rise due to this pull request.

**Comment by paulodamaso** [comment]
@mohamednizar You will when #338 closes

**Comment by fabriciofx** [comment]
@mohamednizar please, fix this PR description puting an issue reference on it.

**Comment by mohamednizar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/344#issuecomment-544624491))

@mohamednizar This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#344](https://github.com/yegor256/jpeek/issues/344) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23344%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@0crat quality accepted

**Comment by 0crat** [comment]
> @0crat quality accepted ([here](https://github.com/yegor256/jpeek/issues/344#issuecomment-549005249))

@paulodamaso Argument "accepted" doesn't match regex `good|bad|acceptable`

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/344#issuecomment-552717668))

@fabriciofx This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#344](https://github.com/yegor256/jpeek/issues/344) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23344%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Pull request merged**
