### PR TITLE
For #220 Added OneMethodCreatesLambda test for TLCOM.

### PR DESCRIPTION
**Pull request by oridan**
For #220 : Added OneMethodCreatesLambda test for TLCOM.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@oridan[/z](https://www.0crat.com/u/oridan) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/jpeek/issues/280#issuecomment-447404155))

@paulodamaso Job `gh:yegor256/jpeek#280` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@2b2b27e5-3878-41a8-a21d-eec9b29fa67f, thread: AsyncProc-2
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/jpeek#280] declared for identity constraint of element "blanks".
```

[0.39.7](https://github.com/zerocracy/farm): CID: [5a79f4bf-d3bc-4f5d-b7e9-df56d6a2bbe1](https://www.0crat.com/footprint/C7JGJ00DP/5a79f4bf-d3bc-4f5d-b7e9-df56d6a2bbe1), Type: "Close job"

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#280` is not assigned, can't get performer

**Pull request closed without merging**
