### PR TITLE
#171: Ignore bridge methods

### PR DESCRIPTION
**Pull request by uurl**
**Issue #171**

Solves #171: Ignore bridge methods
The metric LCOM2 should ignore bridge methods

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#260](https://github.com/yegor256/jpeek/issues/260) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#260](https://github.com/yegor256/jpeek/issues/260); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by uurl** [comment]
@0crat wait #260

**Comment by 0crat** [comment]
> @0crat wait #260 ([here](https://github.com/yegor256/jpeek/issues/260#issuecomment-397908769))

@uurl Job [#260](https://github.com/yegor256/jpeek/issues/260) is not in scope, can't put it on hold

**Comment by uurl** [comment]
Fixes #171

**Comment by uurl** [comment]
This PR closes #171

**Pull request merged**
