### PR TITLE
#143 MWE metric has impediments

### PR DESCRIPTION
**Pull request by uurl**
For #143

**Issue**
MWE metric has impediments. Need to wait for resolving these impediments, add MWE to reports list and cover it by tests.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#237](https://github.com/yegor256/jpeek/issues/237) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at [#237](https://github.com/yegor256/jpeek/issues/237); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@uurl this seems to be a duplicate of another PR?

**Comment by uurl** [comment]
@yegor256 fixed, ready to merge

**Comment by yegor256** [comment]
@uurl see this: https://github.com/yegor256/jpeek/pull/238/files The changes made here I see here again. Why?

**Comment by uurl** [comment]
@yegor256 Sorry, I will fix the PR #238 for the issue #144

**Comment by 0crat** [comment]
The job [#237](https://github.com/yegor256/jpeek/issues/237) is now out of scope

**Pull request closed without merging**
