### PR TITLE
Class as xml externalization

### PR DESCRIPTION
**Pull request by akryvtsun**
The second attempt for this PR

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#369](https://github.com/yegor256/jpeek/issues/369) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#369](https://github.com/yegor256/jpeek/issues/369) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/fbd323e6-58e9-4487-87ec-3a5a93046d69); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by akryvtsun** [comment]
Qulice checks filed

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job [#369](https://github.com/yegor256/jpeek/issues/369) is already in the agenda of @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#369](https://github.com/yegor256/jpeek/issues/369) is now out of scope

**Comment by 0crat** [comment]
Pull request [#369](https://github.com/yegor256/jpeek/issues/369) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
