### PR TITLE
(#120) TCC

### PR DESCRIPTION
**Pull request by llorllale**
as per #120

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#182](https://github.com/yegor256/jpeek/issues/182) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#182](https://github.com/yegor256/jpeek/issues/182) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/451914634). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by llorllale** [comment]
weird... let me check the test failure in the build

**Comment by llorllale** [comment]
@amihaiemil please review

**Comment by llorllale** [comment]
@amihaiemil I'm actually a bit confused by this puzzle. It said that we needed to take into account when two methods are related because they both call a third one. So I implemented that.

But through a cursory look at the PDF `bieman95.pdf` I found this:
> The direct connectivity between methods is determined
from the class abstraction. If there exists one or more
common instance variables between two method abstractions then the two corresponding methods are directly
connected.

So it seems like TCC was already implemented? WDYT?

**Comment by llorllale** [comment]
@amihaiemil I've read the paper and produced [some notes](https://github.com/yegor256/jpeek/issues/120#issuecomment-365953921). I'll be making some changes and let you know. Thank you for your patience

**Comment by llorllale** [comment]
@amihaiemil please review

**Comment by amihaiemil** [comment]
@llorllale 

> I'm actually a bit confused by this puzzle

Sorry, but I can't help you with details related to the metric itself. I don't know them. Here, I am paying more attention to the style, size, Java code in the PR etc and the puzzles.

Basically, since these are sandbox projects, the goal is for the new guys to learn how the model works. If there's a bug in a metric (which is highly expected, since nobody is an expert in theoretical software metrics here), it's not the end of the world. Plus, we have the ARCH, who is supposed to look at the things with more substance :)

**Comment by amihaiemil** [comment]
@llorllale From my point of view, it looks good. Maybe, after the new puzzle is created by 0pdd, go there and link the notes that you've made here :)

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by llorllale** [comment]
@amihaiemil my confusion stemmed from blindly following through with the puzzle's instructions. After reading the PDF for myself I realized that the instructions did not apply to TCC. So I wasted quite a lot of time on this one :)

**Comment by llorllale** [comment]
@yegor256 please merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by amihaiemil** [comment]
@ypshenychka Can you give the verdict here?

**Comment by ypshenychka** [comment]
@amihaiemil Don't worry. I will review as soon as the issue https://github.com/zerocracy/farm/issues/592 is resolved.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ypshenychka** [comment]
@llorllale According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Pull request title explains the problem it is fixing.
Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

Please provide more informative title and description.

**Comment by llorllale** [comment]
@ypshenychka would the following suffice?

* Title: (#120) TCC: advancing implementation
* Description: 
> TCC(C) = NDC(C) / NP(C), where C is the class, NP(C) is a
          maximal possible number of direct or indirect connections - N * (N - 1) / 2,
          NDC(C) is a number of direct connections. Value of the metric is in range [0, 1],
          greater is better.
   See the `bieman95.pdf` paper for more details.

**Comment by ypshenychka** [comment]
@llorllale 
>llorllale commented 5 days ago
weird... let me check the test failure in the build

According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Messages in a job always start with a name of a user they are addressed to.

Please correct your message by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@llorllale Sure. Please go ahead and edit title\description.

**Comment by llorllale** [comment]
@ypshenychka fixed title, description, and that unaddressed message you pointed out

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. Please confirm that you'll try to find at least three problems while future reviews.

**Comment by ypshenychka** [comment]
@llorllale Great. Thanks.

**Comment by amihaiemil** [comment]
@ypshenychka right, I'll try to find more bugs in future tasks. But since these are sandbox projects, I am paying more attention to the methodology :)

**Comment by ypshenychka** [comment]
@amihaiemil thank you

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+240](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+730](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10274](https://www.0crat.com/u/yegor256)

**Pull request merged**
