### PR TITLE
#118 LCC metric has impediments

### PR DESCRIPTION
**Pull request by uurl**
For #118

**Issue**
LCC metric has impediments. Need to wait for resolving these impediments, add LCC to reports list and cover it by tests.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#236](https://github.com/yegor256/jpeek/issues/236) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at [#236](https://github.com/yegor256/jpeek/issues/236); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@uurl you duplicate your code in multiple PRs. Please, make sure each PR has only one piece of functionality.

**Comment by uurl** [comment]
@yegor256 this PR just solves the issue #118

**Comment by yegor256** [comment]
@uurl I see here the changes already merged in https://github.com/yegor256/jpeek/pull/238/files

**Comment by uurl** [comment]
@yegor256 Yes, but I also need to fix the pull #238 for the MWE puzzle

**Comment by 0crat** [comment]
The job [#236](https://github.com/yegor256/jpeek/issues/236) is now out of scope

**Pull request closed without merging**
