### PR TITLE
Added check if file exists

### PR DESCRIPTION
**Pull request by oridan**
PR for #151 

Added an existance verification of the file "/dev/null". If it exists then it is created, otherwise it is created the file "NUL" , Windows compatible version.

### CODE REVIEW

**Comment by 0crat** [comment]
@oridan[/z](https://www.0crat.com/u/oridan) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by oridan** [comment]
@yegor256 please, review this. The codev is failing because the **else** block is never reached on linux, and the **then** block will never be reached on windows. It is a dead lock.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#254` is not assigned, can't get performer

**Pull request merged**
