### PR TITLE
#86 Up year 2018

### PR DESCRIPTION
**Pull request by janczer**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#87` is now in scope, role is `REV`.

**Comment by 0crat** [comment]
This PR `gh:yegor256/jpeek#87` assigned to [@amihaiemil](http://www.0crat.com/u/amihaiemil}). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 15 minutes. Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and [§10](http://datum.zerocracy.com/pages/policy.html#10).

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by yegor256** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@yegor256 rultor failed here, try again pls

**Comment by amihaiemil** [comment]
@janczer check the conflicts pls

**Comment by amihaiemil** [comment]
@janczer Have you found out why there are conflicts?

**Comment by janczer** [comment]
@amihaiemil I have. Now my branch doesn't have any conflict.

**Comment by amihaiemil** [comment]
@janczer there are still some qulice violations in the build, check them out

**Comment by janczer** [comment]
@amihaiemil it's strange, this PR just change year. why it's doesn't build?

**Comment by amihaiemil** [comment]
@janczer Qulice fails with 2 errors, look in the log -- some header is not alligned properly. Qulice is **very** strict, it will complain if a Javadoc doesn't end with a dot (``.``) or if you have traling spaces at the end of a line...

**Comment by amihaiemil** [comment]
@yegor256 we have an ``Ant`` exec failure in the build? Wtf is Ant doing in this project?

**Comment by amihaiemil** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+45](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7745](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#87](https://github.com/yegor256/jpeek/issues/87) is now out of scope

**Pull request merged**
