### PR TITLE
For #180: it is not possible to include the name of the variable.

### PR DESCRIPTION
**Pull request by oridan**
For #180 It was already reported by @llorllale in README.md as a know limitations - The java compiler is known to inline constant variables as per [JLS 13.1].

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#279](https://github.com/yegor256/jpeek/issues/279) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#279](https://github.com/yegor256/jpeek/issues/279); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#279](https://github.com/yegor256/jpeek/issues/279); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by oridan** [comment]
@yegor256 ping.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) everybody who has role `REV` is banned at [#279](https://github.com/yegor256/jpeek/issues/279); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@oridan please resolve the pr conflicts

**Comment by oridan** [comment]
@paulodamaso ping.

**Comment by paulodamaso** [comment]
@oridan What was made in this pr?

**Comment by oridan** [comment]
@paulodamaso I removed the puzzle because it cannot be done. As mentioned before it is a **know limitation**:
> For #180 It was already reported by @llorllale in README.md as a know limitations - The java compiler is known to inline constant variables as per [JLS 13.1].

**Comment by paulodamaso** [comment]
@oridan Okay, I did not understood that it could not be done from the available documentation.

**Comment by 0crat** [comment]
The job [#279](https://github.com/yegor256/jpeek/issues/279) is now out of scope

**Pull request closed without merging**
