### PR TITLE
LCOM2-3 Impl

### PR DESCRIPTION
**Pull request by memoyil**
LCOM2 and LCOM3 Implementation

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#39` is in scope.

**Comment by yegor256** [comment]
@rultor merge

**Comment by memoyil** [comment]
@yegor256 I changed the math signs that possibly cause a merge error. Can we do the merge again?

**Comment by yegor256** [comment]
@rultor merge

**Comment by memoyil** [comment]
@yegor256 I dont know why this is happening. It is building on the travis-ci but could not merged by rultor. I've cleaned the spaces and some special chars again. Sorry for this inconvenience. Could you please try it again?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@memoyil can you please add the text to README about these two metrics? Also we need two PDF articles into the `papers` folder. Thanks!

**Comment by memoyil** [comment]
@yegor256 Ok i will add it

**Pull request merged**
