### PR TITLE
#203 added more tests for OCC metric

### PR DESCRIPTION
**Pull request by mesut**
#203 is solved.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#264](https://github.com/yegor256/jpeek/issues/264) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#264](https://github.com/yegor256/jpeek/issues/264); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by mesut** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/jpeek/issues/264#issuecomment-403527473))

@mesut It's a code review job [#264](https://github.com/yegor256/jpeek/issues/264), can't put it on hold

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#264](https://github.com/yegor256/jpeek/issues/264); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor mertge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#264` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#264](https://github.com/yegor256/jpeek/issues/264) is now out of scope

**Pull request merged**
