### PR TITLE
(#204) Figure out how to extract the concepts from each method of a c…

### PR DESCRIPTION
**Pull request by ilyakharlamov**

### CODE REVIEW

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this pull request

**Comment by 0crat** [comment]
@ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov) this pull request is too small, just 9 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by paulodamaso** [comment]
@ilyakharlamov Please open an issue abou this

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#293` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
