### PR TITLE
Class as xml externalization

### PR DESCRIPTION
**Pull request by akryvtsun**
Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:

  - You made a small amount of changes (less than 100 lines, less than 10 files)
  - You made changes related to only one bug (create separate PRs for separate problems, or leave puzzles)
  - You are ready to defend your changes (there will be a code review)
  - You don't touch what you don't understand
  - You ran the build locally and it passed
  - Title begins with the issue's number, then a short title
  - Description begins with the issue's number, then enumerates the changes - summarized - in bulletpoints
  - Description does not contain GitHub keywords (https://help.github.com/articles/closing-issues-using-keywords/).

This article will help you understand what we are looking for: https://www.yegor256.com/2015/02/09/serious-code-reviewer.html

Thank you for your contribution!

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#366](https://github.com/yegor256/jpeek/issues/366) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#366](https://github.com/yegor256/jpeek/issues/366) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1d9a7414-c1d3-44a5-b2b4-db91affa469c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by akryvtsun** [comment]
Seems test `org.jpeek.web.ReportsTest` is unstable
https://travis-ci.org/yegor256/jpeek/builds/632328904#L1574

**Comment by akryvtsun** [comment]
Will need to remove added pazzler as issue was created for it.

**Comment by 0crat** [comment]
Job [#366](https://github.com/yegor256/jpeek/issues/366) is already in the agenda of @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#366](https://github.com/yegor256/jpeek/issues/366) is now out of scope

**Comment by 0crat** [comment]
Pull request [#366](https://github.com/yegor256/jpeek/issues/366) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
