### PR TITLE
#294 remove puzzle, because tests already done

### PR DESCRIPTION
**Pull request by GnusinPavel**

### CODE REVIEW

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this pull request

**Comment by 0crat** [comment]
@GnusinPavel this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by GnusinPavel** [comment]
@paulodamaso can you review this pull request?

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#347` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by fabriciofx** [comment]
@GnusinPavel please, fix this PR description.

**Comment by GnusinPavel** [comment]
@fabriciofx done

**Comment by GnusinPavel** [comment]
@fabriciofx ping

**Comment by paulodamaso** [comment]
@fabriciofx please go on

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/347#issuecomment-552718282))

@fabriciofx This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#347](https://github.com/yegor256/jpeek/issues/347) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23347%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fabriciofx** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/jpeek/issues/347#issuecomment-552867404))

@fabriciofx There is no quality review for [#347](https://github.com/yegor256/jpeek/issues/347), no performer

**Comment by paulodamaso** [comment]
@fabriciofx It was already merged on https://github.com/yegor256/jpeek/pull/347#issuecomment-538694814

**Comment by fabriciofx** [comment]
@paulodamaso yeah, sorry!

**Pull request merged**
