### PR TITLE
#195 Add a test case

### PR DESCRIPTION
**Pull request by HDouss**
Resolving issue #195 
`$attrs` xslt variable on which we test and filter already takes attributes in skeleton that:
* are not static (so the problem in #156 can not happen)
* in skeleton ops/op text content already has the fully qualified name when it comes to other classes static fields

Added a test case to ensure this.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#399](https://github.com/yegor256/jpeek/issues/399) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/8e30a141-e097-4022-b876-642318104488); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by HDouss** [comment]
@fanifieiev ping

**Comment by HDouss** [comment]
@fanifieiev ping

**Comment by HDouss** [comment]
@fanifieiev ping

**Comment by fanifieiev** [comment]
@HDouss Sorry, but I do not think I can review this PR. 
I have no idea what this test for and what it does.
I will likely refuse this review.

**Comment by fanifieiev** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/399#issuecomment-592199888))

@fanifieiev The user @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) resigned from [#399](https://github.com/yegor256/jpeek/issues/399), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged (job refused in 29 hours), see [§6](http://www.zerocracy.com/policy.html#6): -10 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) everybody who has role `REV` is banned at [#399](https://github.com/yegor256/jpeek/issues/399); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by HDouss** [comment]
@paulodamaso ping

**Comment by paulodamaso** [comment]
@HDouss Thank you!

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#399` is not assigned, can't get performer

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Pull request merged**
