### PR TITLE
Skeleton implements Structure

### PR DESCRIPTION
**Pull request by amihaiemil**
For #100. 

As discussed with the architect, we should have more composability. ``Skeleton`` now implements ``Structure`` so it can be decorated, like this: 

```java
    Structure classes = new MergeTypes(
        new Skeleton(base)
    );
```

``classes`` will now provide the base XML representation (the "skeleton") altered in some way via MergeTypes -- this Structure decorator, as well as Skeleton, should work based on an XSL stylesheet.

Added 2 puzzles: 

1 for continuing implementation of Structure decorators 

1 for adding more ctors to Report. The way it is done now is not so composable since ``Structure.xml()`` has to be called before instantiating the Report.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#157](https://github.com/yegor256/jpeek/issues/157) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/157#issuecomment-363853448))

@amihaiemil This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#157](https://github.com/yegor256/jpeek/issues/157) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 1hr
  * The role is `REV`
  * The job is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) for [3min](http://datum.zerocracy.com/pages/policy.html#8)
  * There is a monetary reward attached
  * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will get 25% of their hourly rate for this job
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil): This user reported the ticket

**Comment by 0crat** [comment]
This pull request [#157](https://github.com/yegor256/jpeek/issues/157) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by carlosmiranda** [comment]
@yegor256 @amihaiemil looks good to me, we can proceed.

**Comment by amihaiemil** [comment]
@yegor256 ping :)

**Comment by yegor256** [comment]
@amihaiemil I don't think it's right. I would go with a different design:

```java
XML xml = new XSLChain( // from jcabi-xml
  new XSLDocument("xsl/skeleton-first.xsl"),
  new XSLDocument("xsl/skeleton-second.xsl"),  
  new XSLDocument("xsl/skeleton-third.xsl"),
).transform(new Skeleton().xml());
```

No new classes, just a collection of new XSL stylesheets.

**Comment by amihaiemil** [comment]
@yegor256 I see. I'll look into it later today.

**Comment by yegor256** [comment]
@amihaiemil I actually forgot about this `XSLChain` class... see how it can make the code look nicer: cb9b37d

**Comment by amihaiemil** [comment]
@yegor256 Done. Now each report has the skeleton transformed according to its metric. But I still think Skeleton should have an interface and be decorated somehow -- now there is also the problem of saving. Only the common skeleton is saved, not the one transformed for each report. :_? It needs to be a proper object :D Should I leave a puzzle about that?

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was successfully finished: +15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), total is [+1245](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9640](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#157](https://github.com/yegor256/jpeek/issues/157) is now out of scope

**Pull request merged**
