### PR TITLE
Status report 2019-02-19.

### PR DESCRIPTION
**Pull request by paulodamaso**
Status report 2019-02-19.

### CODE REVIEW

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#314](https://github.com/yegor256/jpeek/issues/314) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#314` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#314](https://github.com/yegor256/jpeek/issues/314) is now out of scope

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#314` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
