### PR TITLE
(#141) SCOM: cannot test against Bar due to known limitations

### PR DESCRIPTION
**Pull request by llorllale**
For #141 

This PR removes the puzzle and provides the following documentation:

As was [discussed](https://github.com/yegor256/jpeek/issues/141#issuecomment-367745910), SCOM cannot be tested against `Bar` due to [known limitations](https://github.com/yegor256/jpeek#known-limitations).

[Link to `Bar`](https://github.com/yegor256/jpeek/blob/master/src/test/resources/org/jpeek/samples/Bar.java)

Short explanation:
SCOM, like all variants of LCOM, relies on detecting the use of an attribute within a method. Since `Bar` accesses the `final` constant `NAME` inside `getKey`, and since the compiler is optimizing the bytecode in such a way that removes the reference to `NAME`, SCOM would calculate an incorrect value for this test case.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#211](https://github.com/yegor256/jpeek/issues/211) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#211](https://github.com/yegor256/jpeek/issues/211) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/541946717). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by 0crat** [comment]
Job [#211](https://github.com/yegor256/jpeek/issues/211) is already in scope

**Comment by amihaiemil** [comment]
I see, thanks :)

**Comment by amihaiemil** [comment]
@rultor good to merge

**Comment by amihaiemil** [comment]
@llorllale Actually, there is a typo in the README: "the access to the constants are not *be* included in the calculation" -- remove the "be", it shouldn't be there... and also:

Can you add the SCOM example there? It courrently just says "some metrics". Could be "This affects the results of some metrics, like SCOM..."

**Comment by amihaiemil** [comment]
@llorllale And I think we can make the ``Bar`` from the description here a link to the class itself, so the user can reach it easily. Now, if I want to study that Bar class entirely, I have to search it in the repo.

**Comment by amihaiemil** [comment]
@llorllale yes, a general statement is also ok, but something to give an idea about the affected metrics :)

**Comment by llorllale** [comment]
@amihaiemil would this work?

Before
> The java compiler is known to inline constant variables as per [JLS 13.1](https://docs.oracle.com/javase/specs/jls/se8/html/jls-13.html#jls-13.1). This affects the results calculated by some metrics when a method accesses `final` attributes (the access to the constants are not be included in the calculation).

After
> The java compiler is known to inline constant variables as per [JLS 13.1](https://docs.oracle.com/javase/specs/jls/se8/html/jls-13.html#jls-13.1). This affects the results calculated by metrics that take into account access to class attributes if these are `final` constants. All LCOM* and *COM metrics are affected.

Please note though, that we may encounter even more affected metrics in the future. I'd say the majority will be affected.

**Comment by amihaiemil** [comment]
@llorllale Yes, "After" is OK, but since there may be more metrics affected, say "For instance, all LCOM* and *COM metrics are affected"

**Comment by llorllale** [comment]
@amihaiemil done, please review

**Comment by amihaiemil** [comment]
@rultor good to merge

**Comment by amihaiemil** [comment]
@yegor256 can we merge this?

**Comment by yegor256** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@llorllale yet another conflict... :(

**Comment by llorllale** [comment]
@amihaiemil fixed conflicts, please review

**Comment by amihaiemil** [comment]
@yegor256 please, let's try to merge again, conflicts fixed :D

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by amihaiemil** [comment]
@ypshenychka ping

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/yegor256/jpeek/pull/211#issuecomment-368207916) by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

Only two issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by amihaiemil** [comment]
@ypshenychka I confirm (I also edited the message).

**Comment by ypshenychka** [comment]
@amihaiemil Thank you.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/jpeek/issues/211#issuecomment-368810548))

@ypshenychka Job `gh:yegor256/jpeek#211` is not assigned, can't get start time

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+837](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+837](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+1115](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/jpeek/issues/211#issuecomment-368810548))

@ypshenychka The job [#211](https://github.com/yegor256/jpeek/issues/211) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10969](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat pay 8min @ypshenychka

**Comment by 0crat** [comment]
> @0crat pay 8min @ypshenychka ([here](https://github.com/yegor256/jpeek/issues/211#issuecomment-370405643))

@yegor256 The user @@ypshenychka is working for free in this project, see [§49](http://www.zerocracy.com/policy.html#49)

**Comment by yegor256** [comment]
@0crat pay 8min @ypshenychka

**Comment by 0crat** [comment]
> @0crat pay 8min @ypshenychka ([here](https://github.com/yegor256/jpeek/issues/211#issuecomment-370411501))

@yegor256 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.GeneratedMethodAccessor62[-1] java.lang.reflect.InvocationTargetException: null
com.zerocracy.pm.ClaimIn[176] java.lang.IllegalArgumentException: Parameter "reason" not found in "Make payment" among: [comment, job, issue, repo, cause, login, minutes, no-tuition-fee, message]
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
> @0crat pay 8min @ypshenychka ([here](https://github.com/yegor256/jpeek/issues/211#issuecomment-370411501))

@yegor256 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pmo/awards/add_award_points.groovy
sun.reflect.GeneratedMethodAccessor184[-1] java.lang.reflect.InvocationTargetException: null
com.zerocracy.pm.ClaimIn[176] java.lang.IllegalArgumentException: Parameter "reason" not found in "Make payment" among: [comment, job, issue, repo, cause, login, minutes, no-tuition-fee, message]
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
> @0crat pay 8min @ypshenychka ([here](https://github.com/yegor256/jpeek/issues/211#issuecomment-370411501))

@yegor256 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.GeneratedMethodAccessor62[-1] java.lang.reflect.InvocationTargetException: null
com.zerocracy.pm.ClaimIn[176] java.lang.IllegalArgumentException: Parameter "reason" not found in "Make payment" among: [comment, job, issue, repo, cause, login, minutes, message]
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
> @0crat pay 8min @ypshenychka ([here](https://github.com/yegor256/jpeek/issues/211#issuecomment-370411501))

@yegor256 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pmo/awards/add_award_points.groovy
sun.reflect.GeneratedMethodAccessor184[-1] java.lang.reflect.InvocationTargetException: null
com.zerocracy.pm.ClaimIn[176] java.lang.IllegalArgumentException: Parameter "reason" not found in "Make payment" among: [comment, job, issue, repo, cause, login, minutes, message]
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by yegor256** [comment]
@0crat pay 8min @ypshenychka

**Comment by 0crat** [comment]
Direct payment from @yegor256[/z](https://www.0crat.com/u/yegor256): +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Direct payment to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) in #211, which is discouraged, see [§49](http://www.zerocracy.com/policy.html#49): -60 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Pull request merged**
