### PR TITLE
#312 Update PR guidelines in PULL_REQUEST_TEMPLATE

### PR DESCRIPTION
**Pull request by mohamednizar**
#312 
- updated the PULL_REQUEST_TEMPLATE 

**Following new rules  are added**
- You made changes related to only one bug (create separate PRs for separate problems, or leave puzzles)
- You ran the build locally and it passed
- Title begins with the issue's number, then a short title
- Description begins with the issue's number, then enumerates the changes - summarized - in bulletpoints
- Description does not contain GitHub keywords (https://help.github.com/articles/closing-issues-using-keywords/).

### CODE REVIEW

**Comment by 0crat** [comment]
@mohamednizar[/z](https://www.0crat.com/u/mohamednizar) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by mohamednizar** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@mohamednizar Thanks

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#350` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
