### PR TITLE
#57 Parse and provide a SCM link from pom file to App params.

### PR DESCRIPTION
**Pull request by skapral**
Fix for #57

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#179](https://github.com/yegor256/jpeek/issues/179) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#179](https://github.com/yegor256/jpeek/issues/179) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/441153053). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by amihaiemil** [comment]
@skapral The solution is really procedural and lacks tests. Could you implement (or outline the interface + unit tests scaffolding) an object representing the pom.xml and having methid ``scmUrl()``? This way, we keep it OOP and we are able to test that object.

**Comment by skapral** [comment]
@amihaiemil to be honest, whole `Report` class looks procedural for me. I have just adopted to the current design. And it is problematic to test since `App` is instantiated inside it. It definitely is worth refactoring it IMO.

Would the puzzle be enough here?

**Comment by amihaiemil** [comment]
@skapral Yes, definetely leave a puzzle asking to start refactor the class Reports. Personally, I believe ``App`` should take as ctor argument an object of type ``PomXml`` which would represent the ``pom.xml`` file and provide all the stuff jpeek needs from it, including ``scmUrl``. Then, let's see what Yegor says.

**Comment by amihaiemil** [comment]
@skapral forget the puzzle, I've opened a ticket about it since I noticed it's more spread.

**Comment by amihaiemil** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@yegor256 Can we try again here? In the meantime, other PR has been merged succesfully, maybe the code coverage issue has been fixed.

**Comment by yegor256** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@skapral I see now that the ticket is [waiting](https://github.com/yegor256/jpeek/issues/57#issuecomment-364765263) for some issue in jcabi-xml? If so, please close this PR (but don't delete the branch, so you can make another PR when the impediment is gone). Otherwise, I will get taxed for the 10 days rule.

**Comment by amihaiemil** [comment]
@skapral ping

**Comment by amihaiemil** [comment]
@yegor256 See my comment above, I think this PR should be closed until the ticket has impediments. Besides, it has the test coverage issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@skapral I will close it, as requested by @amihaiemil Feel free to submit a new one, when you are ready.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@skapral According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to

Please provide more informative description.

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>The code reviewer found at least three problems in the code.
 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by amihaiemil** [comment]
@ypshenychka Yes, I confirm. Again, we did find a major issue with this PR and 2 others: they are forced to introduce very ugly, procedural code. We opened a ticket about it. I mean, it's not something that can be solved in each PR since it's a lot of effort and it's not the author's fault, the app's architecture drives in that direction :)

**Comment by ypshenychka** [comment]
@amihaiemil That makes sense. However we have another quality remark here.

**Comment by amihaiemil** [comment]
@ypshenychka well, since the PR is closed and not merged, does it matter so much?

**Comment by ypshenychka** [comment]
@amihaiemil Quality is the quality despite in which state the PR is. And we should follow the rules.

**Comment by amihaiemil** [comment]
@skapral ping

**Comment by amihaiemil** [comment]
@skapral ping

**Comment by ypshenychka** [comment]
@skapral Please consider my [remark](https://github.com/yegor256/jpeek/pull/179#issuecomment-367352442) and make appropriate correction.

**Comment by 0crat** [comment]
The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#179](https://github.com/yegor256/jpeek/issues/179), please stop working

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+945](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
This pull request [#179](https://github.com/yegor256/jpeek/issues/179) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/541162638). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by ypshenychka** [comment]
@skapral ping

**Comment by ypshenychka** [comment]
@skapral Please provide informative description.

**Comment by skapral** [comment]
@ypshenychka this PR was declined already because of bad quality. I see no reason to question its quality further, and believe that the fact you've got this PR assigned on you is [mistake](https://github.com/zerocracy/datum/issues/305). @yegor256 FYI.

**Comment by ypshenychka** [comment]
@skapral It's not a mistake. I've asked you to provide informative description to have appropriate documentation in project.

**Comment by skapral** [comment]
@ypshenychka I did some updates, hope they are enough to pass through.

I don't know how about you, but I personally found quite odd the fact that PR, declined on review due to bad quality, is still reviewed on quality afterwards. What is the reason - it is already obvious that the quality is lower the plank. And you may have asked me several times, but theoretically, at this moment I might be rejected from this task hundred of times and be lost in the void (strange actually that I haven't been rejected yet - probably a subject for the future bug on ZC), so you'd never be able to contact me. Since I am not hired anyhow, I am in my own right to leave or ignore the stuff which won't give me profit (like this closed PR), even despite of consequences on the rating. What would you do in this case - still ping me?

PS: Please consider the questions from this comment as rhetorical, since they are off-topic here. I created a separate issue on that - https://github.com/zerocracy/datum/issues/305 - we may continue discussion there.

**Comment by ypshenychka** [comment]
@skapral Thanks. Code reviewer did his job - he reviewed the PR and added his suggestions. And he will be paid only after QA review. So his payment depended on your reaction to my remarks. In any other issue\PR when you will be waiting for payment you can be in similar situation. 
But since @amihaiemil already lost this ticket because of 10 days rule, I can't evaluate this ticket as acceptable anymore. No reason to pay newly assigned code reviewer for no work done here.

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+861](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
> @0crat quality bad ([here](https://github.com/yegor256/jpeek/issues/179#issuecomment-369019803))

@ypshenychka The job [#179](https://github.com/yegor256/jpeek/issues/179) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+11034](https://www.0crat.com/u/yegor256)

**Pull request closed without merging**
