### PR TITLE
#253 remove resolved puzzle

### PR DESCRIPTION
**Pull request by HDouss**
Resolving issue #253 
This puzzle was first added in #9 
It was transformed as an issue by pdd as per #118 

#118 has two merged pull requests:
* #231 that reported the puzzle again and did not add LCC report to App
* #242 that added LCC to the list of reports but did not remove the puzzle

### CODE REVIEW

**Comment by 0crat** [comment]
@HDouss this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by HDouss** [comment]
@paulodamaso as in pr #391 I remerged master in case rultor master branch yaml is fixing the issue.

**Comment by HDouss** [comment]
@paulodamaso ping

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#398` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
