### PR TITLE
Fix #188

### LINKED ISSUE #188: method/@public as xs:boolean does not work when other degrees of visibility are desired
**What I'm trying to do**
Implement `TCC`, which cares about methods of a class that are visible to other classes. This would include default and `protected` access levels, not just `public`

**What I'm getting**
The skeleton only provides `method/@public` indicating whether it is public or not. For TCC, I would like to know whether the method is private or not.

**My proposal**
In `skeleton` we substitute `method/@public` for `method/@visibility` with possible values: `private`, `default`, `protected`, and `public`.

### PR DESCRIPTION
**Pull request by Serranya**
This fixes #188 by introducing a new method attribute: `visibility`.

### CODE REVIEW

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#291](https://github.com/yegor256/jpeek/issues/291) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) everybody who has role `REV` is banned at [#291](https://github.com/yegor256/jpeek/issues/291); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) everybody who has role `REV` is banned at [#291](https://github.com/yegor256/jpeek/issues/291); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@Serranya thanks for the PR

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#291` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#291](https://github.com/yegor256/jpeek/issues/291) is now out of scope

**Pull request merged**
