### PR TITLE
(#134) Documented skeleton.xsd

### PR DESCRIPTION
**Pull request by llorllale**
as per #134

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#189](https://github.com/yegor256/jpeek/issues/189) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#189](https://github.com/yegor256/jpeek/issues/189) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/462018830). The budget is 15 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§27](http://datum.zerocracy.com/pages/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by 0crat** [comment]
Job [#189](https://github.com/yegor256/jpeek/issues/189) is already in scope

**Comment by amihaiemil** [comment]
@llorllale looks good, thanks :)

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by llorllale** [comment]
@yegor256 please merge

**Comment by llorllale** [comment]
@yegor256 please merge

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by ypshenychka** [comment]
@llorllale According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to.

Please change the description to be more informative.

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>The code reviewer found at least three problems in the code.

No issues were found during code review. 
Please confirm that you'll try to find at least three problems while future reviews.

**Comment by llorllale** [comment]
@ypshenychka expanded description

**Comment by amihaiemil** [comment]
@ypshenychka I confirm I'll try to find more bugs in future PRs :)

**Comment by ypshenychka** [comment]
@llorllale @amihaiemil Thank you!

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+255](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+745](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://datum.zerocracy.com/pages/policy.html#28): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10289](https://www.0crat.com/u/yegor256)

**Pull request merged**
