### PR TITLE
remove the stale puzzle

### PR DESCRIPTION
**Pull request by dgarus**
Remove the stale puzzle [#358](https://github.com/yegor256/jpeek/issues/358)

### CODE REVIEW

**Comment by 0crat** [comment]
@dgarus[/z](https://www.0crat.com/u/dgarus) this pull request is too small, just 7 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#377` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
