### PR TITLE
Project report - 2019-01-26

### PR DESCRIPTION
**Pull request by paulodamaso**
Project report - 2019-01-26

### CODE REVIEW

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/jpeek/issues/311#issuecomment-457831057))

@paulodamaso Job `gh:yegor256/jpeek#311` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/jpeek/issues/311#issuecomment-457831057))

@paulodamaso The job [#311](https://github.com/yegor256/jpeek/issues/311) is now out of scope

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#311` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by paulodamaso** [comment]
@rultor release tag is `0.30`

**Pull request merged**
