### PR TITLE
#144 The current implementation of MWE metric expects information

### PR DESCRIPTION
**Pull request by uurl**
For #144

**Problem**
The current implementation of MWE metric expects information about LDA topics.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#238](https://github.com/yegor256/jpeek/issues/238) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at [#238](https://github.com/yegor256/jpeek/issues/238); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#238](https://github.com/yegor256/jpeek/issues/238) is now out of scope

**Pull request closed without merging**
